sudo: required
os:
  - linux
language: python
python:
  - 3.6
env:
  - TEST_SUITE=scripts/travis_test_solc.sh
  - TEST_SUITE=scripts/travis_test_truffle.sh
  - TEST_SUITE=scripts/travis_test_embark.sh
  - TEST_SUITE=scripts/travis_test_dapp.sh
  - TEST_SUITE=scripts/travis_test_etherlime.sh
  - TEST_SUITE=scripts/travis_test_etherscan.sh
branches:
  only:
  - master
  - dev

install:
  - scripts/travis_install.sh

script:
  - $TEST_SUITE

